name: api_client
description: A client that manages api requests
version: 1.0.0
publish_to: none

environment: 
  sdk: ">=2.18.0 <3.0.0"
  flutter: ^3.3.0

dependencies:
  cloud_firestore: ^4.3.1
  crypto: ^3.0.1
  device_info: ^2.0.2
  dio: ^4.0.6
  errors:
    path: ../errors
  equatable: ^2.0.5
  http: ^0.13.5
  json_annotation: ^4.7.0
  storage_repository:
    path: ../storage_repository


dev_dependencies: 
  flutter_test:
    sdk: flutter
  json_serializable: ^6.4.1
  mocktail: ^0.3.0
  mockito: ^5.0.12
  very_good_analysis: ^3.1.0