name: gamez_hub
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"
  flutter: ^3.3.8

dependencies:
  api_client:
    path: packages/api_client
  bottom_navy_bar: ^6.0.0
  cached_network_image: ^3.2.1
  connectivity: ^3.0.6

  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^4.2.1
  flutter_svg: ^1.1.6
  get_it: ^7.2.0
  http: ^0.13.5
  internet_connection_checker: ^0.0.1+4
  font_awesome_flutter: ^9.1.0

dev_dependencies:
  build_runner: ^2.0.6
  flutter_test:
    sdk: flutter
  mockito: ^5.0.12

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/svg/
    - assets/images/png/

  fonts:
    - family: Bolt
      fonts:
        - asset: assets/fonts/bolt-regular.ttf
        - asset: assets/fonts/bolt-semibold.ttf
          weight: 700
    - family: Poppings
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
