name: push_notification_repository
description: A dart package that manages push notifications.
publish_to: none

environment: 
  sdk: ">=2.18.0 <3.0.0"
  flutter: ^3.3.0

dev_dependencies:
  build_runner: ^2.1.7
  coverage: ^1.0.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
  mocktail: ^0.2.0
  test: ^1.17.10
  very_good_analysis: ^3.0.0