name: authentication_repository
description: dart package that manages user authentication
publish_to: none

environment: 
  sdk: ">=2.18.4 <3.0.0"
  flutter: ^3.3.8

dependencies:
  api_client:
    path: ../api_client
  dartz: ^0.10.1
  equatable:  ^2.0.5
  errors:
    path: ../errors
  json_annotation: ^4.7.0
  meta: ^1.7.0
  storage_repository:
    path: ../storage_repository
  very_good_analysis: ^3.0.0
  dartdoc: ^6.1.1


dev_dependencies:
  build_runner: ^2.0.6
  coverage: ^1.0.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.4.1
  mocktail: ^0.3.0