name: authentication_repository
description: dart package that manages user authentication
publish_to: none

environment: 
  sdk: ">=2.18.4 <3.0.0"
  flutter: ^3.3.8

dependencies:
  api_client:
    path: ../api_client
  dartdoc: ^6.1.1
  dartz: ^0.10.1
  equatable:  ^2.0.5
  errors:
    path: ../errors
  firebase_auth: ^4.0.2
  firebase_core: ^2.1.0
  # Unfortunately, a breaking change was introduced in 4.5.2.
  # https://github.com/firebase/flutterfire/issues/9806
  firebase_core_platform_interface: 4.5.3
  flutter_facebook_auth: ^5.0.8
  google_sign_in: ^5.4.2
  json_annotation: ^4.7.0
  meta: ^1.7.0
  storage_repository:
    path: ../storage_repository
  very_good_analysis: ^3.0.0
  


dev_dependencies:
  build_runner: ^2.0.6
  coverage: ^1.0.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.4.1
  mocktail: ^0.3.0